# Copyright (c) 2026, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Extract unchanged vLLM 0.25.1 definitions into a standalone package.

Usage: uv run --no-project tools/vllm_postprocessing/vendor.py /path/to/vllm-0.25.1
Only import scaffolding and explicitly selected class members differ. The
manifest records each copied fragment and the SHA256 of its complete source.
"""

import argparse
import ast
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEST = ROOT / "nemo_rl/_vendor/vllm"
HEADER = "# SPDX-License-Identifier: Apache-2.0\n# SPDX-FileCopyrightText: Copyright contributors to the vLLM project\n# Generated by tools/vllm_postprocessing/vendor.py; do not edit.\nfrom __future__ import annotations\n\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    args = parser.parse_args()
    manifest = {
        "version": "0.25.1",
        "upstream": "https://github.com/vllm-project/vllm/tree/v0.25.1",
        "files": {},
    }

    def generate(
        name: str,
        imports: str,
        selections: list[tuple[str, list[str] | dict[str, list[str] | None] | None]],
    ) -> None:
        text = HEADER + imports + "\n\n"
        fragments = []
        for path, names in selections:
            source = (args.source / "vllm" / path).read_text()
            lines = source.splitlines(keepends=True)
            tree = ast.parse(source)
            nodes = {
                n.name: n
                for n in tree.body
                if isinstance(n, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef))
            }
            for node in tree.body:
                if isinstance(node, ast.Assign):
                    for target in node.targets:
                        if isinstance(target, ast.Name):
                            nodes[target.id] = node
                elif isinstance(node, ast.AnnAssign) and isinstance(
                    node.target, ast.Name
                ):
                    nodes[node.target.id] = node
            if names is None:
                names = list(nodes)
            if isinstance(names, list):
                names = {n: None for n in names}
            # Include same-file helper definitions used by the selected objects.
            pending = list(names)
            while pending:
                key = pending.pop()
                selected = nodes[key]
                if isinstance(selected, ast.ClassDef) and names[key] is not None:
                    selected = ast.Module(
                        body=[
                            child
                            for child in selected.body
                            if getattr(child, "name", None) in names[key]
                            or (
                                isinstance(child, ast.AnnAssign)
                                and isinstance(child.target, ast.Name)
                                and child.target.id in names[key]
                            )
                        ],
                        type_ignores=[],
                    )
                for ref in ast.walk(selected):
                    if (
                        isinstance(ref, ast.Name)
                        and ref.id in nodes
                        and ref.id not in names
                    ):
                        names[ref.id] = None
                        pending.append(ref.id)
            names = dict(sorted(names.items(), key=lambda item: nodes[item[0]].lineno))

            def emit(node: ast.stmt) -> None:
                nonlocal text
                start = min(
                    [node.lineno]
                    + [d.lineno for d in getattr(node, "decorator_list", [])]
                )
                fragment = "".join(lines[start - 1 : node.end_lineno])
                text += fragment + "\n\n"
                fragments.append(
                    {
                        "source": path,
                        "start": start,
                        "end": node.end_lineno,
                        "sha256": hashlib.sha256(fragment.encode()).hexdigest(),
                    }
                )

            for obj, members in names.items():
                node = nodes[obj]
                if members is None:
                    emit(node)
                else:
                    text += (
                        f"class {node.name}"
                        + (
                            "(nn.Module)"
                            if obj in ("Sampler", "TopKTopPSampler")
                            else "(OpenAIBaseModel)"
                            if obj == "ChatCompletionRequest"
                            else "(GenerateBaseServing)"
                            if obj == "OpenAIServingChat"
                            else ""
                        )
                        + ":\n"
                    )
                    for child in node.body:
                        key = (
                            child.name
                            if isinstance(
                                child, (ast.FunctionDef, ast.AsyncFunctionDef)
                            )
                            else child.target.id
                            if isinstance(child, ast.AnnAssign)
                            and isinstance(child.target, ast.Name)
                            else None
                        )
                        if key in members:
                            emit(child)
            manifest["files"].setdefault(
                path,
                {
                    "sha256": hashlib.sha256(source.encode()).hexdigest(),
                    "url": f"https://raw.githubusercontent.com/vllm-project/vllm/v0.25.1/vllm/{path}",
                },
            )
        text = text.replace(
            "        from vllm.parser.engine.incremental_lexer import terminals_from_literals",
            "        # terminals_from_literals is vendored in this module.",
        )
        text = text.replace(
            "        from vllm.parser.engine.incremental_lexer import LexerShape",
            "        # LexerShape is vendored in this module.",
        )
        text = text.replace(
            "        from vllm.tool_parsers.structural_tag_registry import get_model_structural_tag",
            '        raise NotImplementedError("Structured decoding is not supported by this adapter")',
        )
        (DEST / name).write_text(text)
        manifest.setdefault("generated", {})[name] = {
            "sha256": hashlib.sha256(text.encode()).hexdigest(),
            "fragments": fragments,
        }

    generate(
        "sampling.py",
        """from dataclasses import dataclass
from itertools import chain
from collections.abc import Iterable, Iterator
import torch
import torch.nn as nn
from .support import init_logger
from .sampling_support import current_platform, HAS_TRITON, apply_top_k_top_p_triton
_SAMPLING_EPS = 1e-5""",
        [
            ("v1/sample/logits_processor/state.py", ["LogitsProcessors"]),
            ("v1/sample/metadata.py", ["SamplingMetadata"]),
            (
                "v1/sample/ops/topk_topp_sampler.py",
                {
                    **{
                        n: None
                        for n in [
                            "apply_top_k_top_p",
                            "apply_top_k_top_p_pytorch",
                            "apply_top_k_only",
                            "empty_exponential_noise_like",
                            "sample_with_exponential_noise",
                            "random_sample",
                        ]
                    },
                    "TopKTopPSampler": ["forward_native"],
                },
            ),
            (
                "v1/sample/sampler.py",
                {
                    "Sampler": [
                        "apply_temperature",
                        "greedy_sample",
                        "sample",
                        "compute_logprobs",
                    ]
                },
            ),
        ],
    )
    # Retain the complete Triton kernels, including the dispatch thresholds and lookup tables.
    path = "v1/sample/ops/topk_topp_triton.py"
    source = (args.source / "vllm" / path).read_text()
    generated = (
        source.replace(
            "from vllm.triton_utils import tl, triton",
            "import triton\nimport triton.language as tl",
        )
        .replace(
            "from vllm.utils.math_utils import next_power_of_2",
            "from .sampling_support import next_power_of_2",
        )
        .replace(
            "from vllm.utils.platform_utils import num_compute_units",
            "from .sampling_support import num_compute_units",
        )
    )
    (DEST / "topk_topp_triton.py").write_text(generated)
    manifest["files"][path] = {
        "sha256": hashlib.sha256(source.encode()).hexdigest(),
        "url": f"https://raw.githubusercontent.com/vllm-project/vllm/v0.25.1/vllm/{path}",
    }
    manifest.setdefault("generated", {})["topk_topp_triton.py"] = {
        "sha256": hashlib.sha256(generated.encode()).hexdigest(),
        "import_rewrites_only": True,
    }

    engine_names = [
        "OpenAIBaseModel",
        "ErrorInfo",
        "ErrorResponse",
        "PromptTokenUsageInfo",
        "UsageInfo",
        "PerRequestTimingMetrics",
        "RequestResponseMetadata",
        "StreamOptions",
        "FunctionDefinition",
        "FunctionCall",
        "ToolCall",
        "DeltaFunctionCall",
        "DeltaToolCall",
        "ExtractedToolCallInformation",
        "DeltaMessage",
        "GenerationError",
    ]
    chat_names = [
        "ChatMessage",
        "ChatCompletionLogProb",
        "ChatCompletionLogProbsContent",
        "ChatCompletionLogProbs",
        "ChatCompletionResponseChoice",
        "ChatCompletionResponse",
        "ChatCompletionResponseStreamChoice",
        "ChatCompletionToolsParam",
        "ChatCompletionNamedFunction",
        "ChatCompletionNamedToolChoiceParam",
    ]
    request_fields = [
        "messages",
        "model",
        "logprobs",
        "top_logprobs",
        "n",
        "stream",
        "stream_options",
        "tools",
        "tool_choice",
        "include_reasoning",
        "parallel_tool_calls",
        "chat_template_kwargs",
        "return_tokens_as_token_ids",
        "return_token_ids",
        "return_prompt_text",
        "echo",
        "add_generation_prompt",
        "continue_final_message",
        "check_tool_usage",
        "check_logprobs",
        "check_generation_prompt",
    ]
    generate(
        "protocol.py",
        """import logging
import time
from http import HTTPStatus
from typing import Any, ClassVar, Literal
from uuid import uuid4
from dataclasses import dataclass
from pydantic import BaseModel, ConfigDict, Field, model_validator, model_serializer
from openai.types.chat import ChatCompletionMessageParam
from openai.types.chat.chat_completion_audio import ChatCompletionAudio as OpenAIChatCompletionAudio
from openai.types.chat.chat_completion_message import Annotation as OpenAIAnnotation
from .support import VLLMValidationError, init_logger, random_uuid
logger = init_logger(__name__)""",
        [
            ("logprobs.py", ["Logprob"]),
            ("entrypoints/chat_utils.py", ["make_tool_call_id"]),
            ("entrypoints/openai/engine/protocol.py", engine_names),
            (
                "entrypoints/openai/chat_completion/protocol.py",
                {
                    **{n: None for n in chat_names},
                    "ChatCompletionRequest": request_fields,
                },
            ),
        ],
    )

    generate(
        "parsers.py",
        """import ast
import contextlib
import dataclasses
import functools
import json
import math
import warnings
from abc import abstractmethod
from collections.abc import Callable, Iterable, Iterator, Sequence
from contextlib import contextmanager
from dataclasses import dataclass, field
from enum import Enum, auto
from functools import cached_property
from itertools import islice
from typing import Any, TYPE_CHECKING, TypeAlias
import regex as re
from pydantic import TypeAdapter, ValidationError
from openai.types.responses.tool import Tool as ResponsesTool
from openai.types.responses import FunctionTool, ToolChoiceFunction, ResponseFunctionToolCall
from .protocol import *
from .support import envs, init_logger, record_tool_parser_invocation, ResponsesRequest, NamespaceTool, get_tool_call_id_type
logger = init_logger(__name__)""",
        [
            (
                "tool_parsers/utils.py",
                [
                    "safe_literal_eval",
                    "ResponsesToolCallName",
                    "find_tool_properties",
                    "find_tool_name",
                    "extract_types_from_schema",
                    "coerce_to_schema_type",
                ],
            ),
            ("reasoning/abs_reasoning_parsers.py", ["ReasoningParser"]),
            ("reasoning/basic_parsers.py", ["BaseThinkingReasoningParser"]),
            (
                "reasoning/deepseek_r1_reasoning_parser.py",
                ["DeepSeekR1ReasoningParser"],
            ),
            ("tool_parsers/abstract_tool_parser.py", ["ToolParser"]),
            ("parser/utils.py", ["count_history_tool_calls"]),
            (
                "parser/abstract_parser.py",
                ["StreamState", "Parser", "DelegatingParser"],
            ),
            ("parser/engine/events.py", None),
            ("parser/engine/parser_engine_config.py", None),
            ("parser/engine/incremental_lexer.py", None),
            ("parser/engine/token_id_scanner.py", None),
            ("parser/engine/streaming_parser_engine.py", None),
            ("parser/engine/parser_engine.py", None),
            ("parser/qwen3.py", None),
            ("parser/nemotron_v3.py", None),
            ("parser/engine/adapters.py", None),
        ],
    )
    generate(
        "response.py",
        """import asyncio
import base64
import io
import time
from http import HTTPStatus
from collections.abc import Sequence as GenericSequence, MutableSequence
from dataclasses import dataclass
from typing import Any, TypeVar
import numpy as np
from .protocol import *
from .support import init_logger
logger = init_logger(__name__)""",
        [
            ("outputs.py", ["CompletionOutput", "RequestOutput"]),
            (
                "entrypoints/generate/base/serving.py",
                {
                    "format_token_id_placeholder": None,
                    "clamp_prompt_logprobs": None,
                    "GenerateBaseServing": ["_raise_if_error", "_get_decoded_token"],
                },
            ),
            (
                "entrypoints/serve/utils/tool_calls_utils.py",
                ["maybe_filter_parallel_tool_calls"],
            ),
            (
                "entrypoints/openai/chat_completion/serving.py",
                {
                    "_make_prompt_tokens_details": None,
                    "OpenAIServingChat": [
                        "get_chat_request_role",
                        "chat_completion_full_generator",
                        "_get_top_logprobs",
                        "_create_chat_logprobs",
                    ],
                },
            ),
        ],
    )
    (DEST / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    (DEST / "LICENSE").write_text((args.source / "LICENSE").read_text())


if __name__ == "__main__":
    main()
